Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-25.04"
  config.vm.box_version = "202510.26.0"
  config.vm.define "ubuntu" do |web|
    web.vm.network "private_network", ip: "192.168.0.10"
  end 
end